### ISSUE TITLE
Teleoperation - can't display camera stream in VR

### ISSUE THREAD

**Issue by PositiveBeat** [energinet-digitalisering/energirobotter-elrik#7]
### Description of the bug

It loads forever when trying to go into VR using the Vuer client app. After a few tries of quitting and reconnecting, I got this error message from the terminal:

```
[teleoperation_node-3] Missing return statement on request handler
[teleoperation_node-3] Traceback (most recent call last):
[teleoperation_node-3]   File "/home/drone/.local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 653, in finish_response
[teleoperation_node-3]     prepare_meth = resp.prepare
[teleoperation_node-3] AttributeError: 'NoneType' object has no attribute 'prepare'
[teleoperation_node-3] Missing return statement on request handler
[teleoperation_node-3] Traceback (most recent call last):
[teleoperation_node-3]   File "/home/drone/.local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 653, in finish_response
[teleoperation_node-3]     prepare_meth = resp.prepare
[teleoperation_node-3] AttributeError: 'NoneType' object has no attribute 'prepare'
```

**Comment by PositiveBeat** [comment]
The error was not the cause, but instead this line: `session.set @ Scene()`.
Fixed in commit https://github.com/energinet-digitalisering/energirobotter-elrik/commit/925501f5b485c7bf5cbf66b867ae6bd2066b690b.
